### ISSUE TITLE
Wrong locale  'pt_PT' => _('Portuguese (Brazil)'),

### ISSUE THREAD

**Issue by bieldp** [niallkennedy/open-graph-protocol-tools#5]
There is a issue on line 309. The locale settings says 'pt_PT' => _('Portuguese (Brazil)') where it should be 'pt_PT' => _('Portuguese (Portugal)')

Also it should be add another locale setting  'pt_BR' => _('Portuguese (Brazil)')

**Comment by jonursenbach** [comment]
Submit a pull request?

**Comment by niallkennedy** [comment]
Thanks for the report. I will diff against the current Facebook locales XML and update the array with the latest.

**Comment by niallkennedy** [comment]
label should be fixed in ac1f238f52088be9fb220df0dd9ef3b2fb452b82
